``7-base_geometry`` module
======================

Importing BaseGeometry class:

    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry


Test Cases
-------------------

::

    >>> bg = BaseGeometry()
    >>> type(bg)
    <class '7-base_geometry.BaseGeometry'>

    >>> print(bg) # doctest: +ELLIPSIS
    <7-base_geometry.BaseGeometry object at...>

    >>> bg = BaseGeometry(None)
    Traceback (most recent call last):
    TypeError: BaseGeometry() takes no arguments

    >>> bg.integer_validator(None)
    Traceback (most recent call last):
    TypeError: integer_validator() missing 1 required positional argument: 'value'

    >>> bg.integer_validator()
    Traceback (most recent call last):
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

    >>> bg.integer_validator("my_int", 12)
    >>> bg.integer_validator("width", -100)
    Traceback (most recent call last):
    ValueError: width must be greater than 0

    >>> bg.integer_validator("height", 0)
    Traceback (most recent call last):
    ValueError: height must be greater than 0

    >>> bg.integer_validator("name", "John")
    Traceback (most recent call last):
    TypeError: name must be an integer

    >>> bg.integer_validator("name", None)
    Traceback (most recent call last):
    TypeError: name must be an integer

    >>> bg.integer_validator("age", 0)
    Traceback (most recent call last):
    ValueError: age must be greater than 0

    >>> bg.integer_validator("distance", -1)
    Traceback (most recent call last):
    ValueError: distance must be greater than 0

    >>> bg.integer_validator("distance", 0.5)
    Traceback (most recent call last):
    TypeError: distance must be an integer

    >>> bg.integer_validator("name", [2, 1])
    Traceback (most recent call last):
    TypeError: name must be an integer

    >>> bg.integer_validator([1, 2], [2, 1])
    Traceback (most recent call last):
    TypeError: [1, 2] must be an integer

    >>> bg.integer_validator([1, 2], 20)

    >>> bg.integer_validator("name", True)
    Traceback (most recent call last):
    TypeError: name must be an integer

    >>> bg.integer_validator("name", {1, 2})
    Traceback (most recent call last):
    TypeError: name must be an integer

    >>> bg.integer_validator("name", (1,))
    Traceback (most recent call last):
    TypeError: name must be an integer
